### PR TITLE
Modified the whole repository.

### PR DESCRIPTION
**Pull request by Kryst4lskyxx**

### CODE REVIEW

**Comment by iivanoo** [comment]
Does the structure of the folders describe in the readme correspond to the folders' structure in the repo?

**Comment by Kryst4lskyxx** [comment]
> Does the structure of the folders describe in the readme correspond to the folders' structure in the repo?

Should I modify the whole repo or just the README?

**Comment by iivanoo** [comment]
> > Does the structure of the folders describe in the readme correspond to the folders' structure in the repo?
> 
> Should I modify the whole repo or just the README?

The whole repo, please :)

**Comment by Kryst4lskyxx** [comment]
I've now modify the whole repo.

**Comment by iivanoo** [comment]
Ok, thanks. Can you please correct the typo in the title of the PR? Then, I will merge it.

**Comment by Kryst4lskyxx** [comment]
> Ok, thanks. Can you please correct the typo in the title of the PR? Then, I will merge it.

Sure, done.

**Comment by iivanoo** [comment]
Hmm, no, sorry, it still says "Modefied" instead of "Modified"

**Comment by Kryst4lskyxx** [comment]
> Hmm, no, sorry, it still says "Modefied" instead of "Modified"

Oh! Sorry, it has been corrected now.

**Pull request merged**
